Chore: Update build scripts in `package.json` and code to get URL in `Party.tsx` as part of the deployment
nickytonline/astro-partykit-starter pull request #12
Opened 2023-12-31 10:51 UTC by adiati98

## Description

This PR holds below changes:

- Update the build scripts to include `partykit deploy` in `package.json`.
- Update the code for getting the Partykit URL in `Party.tsx`.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #10 

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-12-31 11:39 UTC, adiati98 commented
@nickytonline is there anything I should run locally to test this out?

2023-12-31 13:03 UTC, nickytonline commented
When you run `npm run build` you should see it build successfully, including partykit.

If you get a build error, you may need to initialize partykit for yourself. See their docs, https://docs.partykit.io/.

To see if this is working on deploys, all the checks should have passed and if you go to the deploy preview, you should see your messages appear if you send a message.

2023-12-31 14:02 UTC, adiati98 commented
@nickytonline I have a couple of questions and issues:

- I ran `npm install` but I didn't commit changes in `.husky/_/husky.sh` and `package-lock.json`. Should I commit them?
- The deploy/netlify status is: `Expected — Waiting for status to be reported`. So I'm not sure if the checks are actually passed or not.
- I ran `npm run build` and got no error. So I proceeded with `npm start`. I could submitted username and room id, but when I enter message and hit the submit button, it didn't print out the message. What kind of behaviour do we expect here?
  
  ![partykit live preview](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/ff514a20-520d-4e16-8408-82f5ba22e679)

2023-12-31 15:39 UTC, Satoshi-Sh approved these changes
The updates look good :+1: 

About the unsent messages, the server is not running on the npm run dev.
![Screenshot from 2023-12-31 09-29-10](https://github.com/nickytonline/astro-partykit-starter/assets/73622805/6fcca50e-237c-419f-86bf-3d0eaf42ed79)

```"dev": "partykit dev & astro dev",``` in the package.json is missing "&". 
Once I replaced it with ```"dev": "partykit dev && astro dev",```. It's all good

I think you can update it in this PR.

2023-12-31 17:00 UTC, adiati98 commented
@Satoshi-Sh good catch! Thanks! 👍

Just wondering, in which localhost did you run it locally?

I've added the `&`. And when I run `npm run dev`, I clicked "b" to open a browser as stated in the terminal:

![npm run dev 404 not found](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/599e7fa7-599f-4513-95b0-73f4c4f1848a)

But I got "Not found" as below:

![localhost 1999](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/45608131-7809-4fc6-9ce1-a161e2f513db)

This behaviour is the same with if there is a single `&` in the "dev" scripts.
That was the reason I ran `npm start` because we also have "start" in the scripts and open it on `http://localhost:4321/`.

2023-12-31 17:15 UTC, nickytonline commented
Good catch @Satoshi-Sh. I was running it separately when I first created the project.

2023-12-31 17:19 UTC, Satoshi-Sh commented
![Screenshot from 2023-12-31 11-16-43](https://github.com/nickytonline/astro-partykit-starter/assets/73622805/fba78b9f-4e71-448d-9fef-88e33fc03c33)

`npm run dev` will run client and server, so you just need to open localhost:4321 on your browser.  @adiati98

2023-12-31 19:48 UTC, adiati98 commented
@Satoshi-Sh @nickytonline I added the missing `&` and pushed the change.

---

I don't get the result as Satoshi had in my terminal when running `npm run dev`.

### Local Environment

Here how set up the local environment:

- Run `npm install`.
- Run `npm run dev`.

Is there any missing steps here?

### Behavior

1. After 10 minutes running `npm run dev`, nothing happened. Here is the screenshot: 

    ![npm run dev warning 1](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/dc9100a4-8d19-4209-88c9-26ef054cc87d)

    The `[pk:inf] GET / 404 Not Found (14ms)` was an ettempt to run `localhost: 1999` by typing "b" to open a browser after 10 minutes.

2. Then I clicked `[x] to exit` and got this:

    ![ready after x](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/d04d3ed6-928d-407f-bfc4-e62fa67d47ef)

3. So I opened the `http://localhost:4321/` and it still gave no print out. On console: `partysocket_react.js?v=ec93f343:399 WebSocket connection to 'ws://localhost:1999/party/01?_pk=8a2155a0-74b7-4b38-9f3f-4dfa61ef56ca' failed:` as screenshot below:

    ![console log partykit](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/dd8f2c44-2e42-43bb-bf29-67f4deb0458c)

2023-12-31 20:32 UTC, Satoshi-Sh commented
It looks like && is different in Windows. It runs commands one by one. Once you stop the first command "party-kit dev", the second "astro dev" will run.  [referece](https://stackoverflow.com/questions/8055371/how-do-i-run-two-commands-in-one-line-in-windows-cmd#:~:text=%26%26%20%5B...%5D%0Acommand1%20%26%26%20command2%0AUse%20to%20run%20the%20command%20following%20%26%26%20only%20if%20the%20command%20preceding%20the%20symbol%20is%20successful.%20Cmd.exe%20runs%20the%20first%20command%2C%20and%20then%20runs%20the%20second%20command%20only%20if%20the%20first%20command%20completed%20successfully.)

I think "partykit dev & astro dev" will be working fine in Windows. 
I would put commands like this. 

```
"dev-win": "partykit dev & astro dev",
"dev-mac": "partykit dev && astro dev", 
```
Sorry for letting you @ayu back and forth.  

Let me know if you have another solution on this @nickytonline

2023-12-31 20:46 UTC, adiati98 commented
No worries at all, @Satoshi-Sh! 😄
Thanks for bearing with my long comments!!! 

I'll try the solution later on while waiting for @nickytonline response. 😊

2023-12-31 21:30 UTC, adiati98 commented
@Satoshi-Sh, an update. It behaves the same with double `&`.

2023-12-31 22:05 UTC, Satoshi-Sh commented
I see. Then Windows users need to run the two commands in different terminals.
I would add `"start-server": "partykit dev",` to the scripts.

You can command `npm start` on one terminal and `npm run start-server` in another terminal.  

You can keep "dev": "partykit dev && astro dev", as is.

Is it better to add an instruction on how to run this application locally to README.md for Windows users? I believe Linux and Mac users can just run `npm run dev`.

2023-12-31 22:54 UTC, adiati98 commented
> I see. Then Windows users need to run the two commands in different terminals. I would add `"start-server": "partykit dev",` to the scripts.
> 
> You can command `npm start` on one terminal and `npm run start-server` in another terminal.
> 
> You can keep "dev": "partykit dev && astro dev", as is.
> 
> Is it better to add an instruction on how to run this application locally to README.md for Windows users? I believe Linux and Mac users can just run `npm run dev`.

This solution works!!!! 🎉

If @nickytonline agree with this, I can apply this and update the docs later. 👍

2024-01-01 12:10 UTC, adiati98 commented
@nickytonline @Satoshi-Sh 

If what we have in this PR now works for Mac and Linux, we can merge this as is. 👍

I will do some research and raise another issue to add solution for Windows.

2024-01-01 12:39 UTC, nickytonline commented
Let's merge as is, and if you can create an issue for Windows @adiati98 we can get it sorted there. There's `nom-run-all` and `concurrently` packages that can do this. I think I'd probably go with `concurrently` based on this article. https://www.swyx.io/parallel-npm-scripts

2024-01-01 12:42 UTC, nickytonline requested changes
This is looking good @adiati98. One small change request.

2024-01-01 12:42 UTC, nickytonline commented on package.json
> +    "dev": "partykit dev && astro dev",
We'll sort this out in the Windows issue that will get created. Below works on non-Windows environments.

```suggestion
    "dev": "partykit dev & astro dev",
```

2024-01-01 14:57 UTC, adiati98 commented
> This is looking good @adiati98. One small change request.

I've fixed it, @nickytonline 👍

And I'll open an issue sometime today. 😊

2024-01-02 00:10 UTC, nickytonline commented
I'm on vacation at the moment, but should get to testing this out before end of week.

2024-01-02 01:26 UTC, nickytonline approved these changes
Thanks @adiati98! 🚢

2024-01-02 01:27 UTC, merged