feat: adding playwright testing to starter kit
nickytonline/astro-partykit-starter pull request #63
Opened 2024-02-03 20:41 UTC by jdwilkin4

## Description

This PR does the following: 

- [x] installing Playwright to starter kit
- [x] add test for joining a room with username
- [x] add test for joining as anonymous user to the default room
- [x] add test for the modal
- [x] add test for the sending messages
- [x] updates the `README` to mention testing with playwright

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #53 

## Mobile & Desktop Screenshots/Recordings

<img width="1124" alt="Screenshot 2024-02-03 at 12 39 35 PM" src="https://github.com/nickytonline/astro-partykit-starter/assets/67210629/130c027a-bd45-424c-bc72-c8e17b576372">

## Steps to QA

1. pull down this branch
2. install dependencies 
3. run `npx playwright test` in the project directory
4. run `npx playwright show-report` to see results on `http://localhost:9323`

## Added to documentation?

- [x] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-04 01:02 UTC, nickytonline commented
I got the test running via the CLI and the UI of Playwright, but even after installing the dependencies, I had to run `npm playwright install` and then things started working.

```bash
❯ npx playwright test     

Running 12 tests using 5 workers
  1) [chromium] › send-messages.spec.ts:3:1 › user sending a message ─────────

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  2) [firefox] › join-room.spec.ts:3:1 › join room with username and room number 

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/firefox-1438/firefox/Nightly.app/Contents/MacOS/firefox
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  3) [chromium] › modal.spec.ts:3:1 › user leaving a room ────────────────────

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  4) [chromium] › join-room.spec.ts:13:1 › join room as anonymous user and default room 

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  5) [chromium] › join-room.spec.ts:3:1 › join room with username and room number 

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  6) [webkit] › join-room.spec.ts:3:1 › join room with username and room number 

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/webkit-1967/pw_run.sh
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  7) [firefox] › join-room.spec.ts:13:1 › join room as anonymous user and default room 

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/firefox-1438/firefox/Nightly.app/Contents/MacOS/firefox
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  8) [webkit] › join-room.spec.ts:13:1 › join room as anonymous user and default room 

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/webkit-1967/pw_run.sh
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


  9) [firefox] › modal.spec.ts:3:1 › user leaving a room ─────────────────────

    Error: browserType.launch: Executable doesn't exist at /Users/nicktaylor/Library/Caches/ms-playwright/firefox-1438/firefox/Nightly.app/Contents/MacOS/firefox
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                            [...]

2024-02-04 01:05 UTC, nickytonline requested changes
This is really great @jdwilkin4! Thanks for putting up this PR! Just a few change requests.

2024-02-04 01:05 UTC, nickytonline commented on tests/modal.spec.ts
> +import { test } from "@playwright/test";
naming (blocking): The name of the test is too generic. Consider calling it something like`leave-room.spec.ts` which is more in line with the names of the other tests.

2024-02-04 01:08 UTC, nickytonline commented
This is a great first step to getting end-to-end (E2E) testing in place for this template project. In another pull request, we should look into making this part of the deployment process so that we can fail a build if the E2E tests fail.

Also, to get it set up for testing in the continuous integration/continuous deployment (CI/CD) flow, we'll need to set up an instance of our party kit app for that. I can help with this if you want to work on this together @jdwilkin4.

2024-02-04 21:26 UTC, jdwilkin4 commented
>  In another pull request, we should look into making this part of the deployment process so that we can fail a build if the E2E tests fail.

Yeah, I think that is a great idea 👍 

> Also, to get it set up for testing in the continuous integration/continuous deployment (CI/CD) flow, we'll need to set up an instance of our party kit app for that. I can help with this if you want to work on this together @jdwilkin4.

I would be down for that 👍

2024-02-05 05:02 UTC, nickytonline approved these changes
Thanks for making the changes @jdwilkin4! One small change request, but I'm going to go ahead and approve.

2024-02-05 05:02 UTC, nickytonline commented on README.md
> +This starter kit uses [Playwright](https://playwright.dev/) for end-to-end testing. To install Playwright, run `npm install playwright` in the terminal.
```suggestion
This starter kit uses [Playwright](https://playwright.dev/) for end-to-end testing. To install Playwright, run `npx install playwright` in the terminal.
```

2024-12-19 15:21 UTC, closed without merging